@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Diagrama de Componentes - Sistema de Gestão de Ciclos de Estudo

Person(user, "Concurseiro / Vestibulando", "Usuário que utiliza o sistema para gerenciar seus estudos.")
Person_Ext(admin, "DevOps / Admin", "Monitora a saúde do sistema.")

System_Ext(authSystem, "Serviço de Autorização", "Autoriza via OIDC/OAuth2")
System_Ext(emailSystem, "Provedor de E-mail/Push", "AWS SES / Firebase")
System_Ext(concursosApi, "API de Concursos", "Fornece dados de Concursos")

System_Ext(prometheus, "Prometheus",  "Coleta e armazena métricas (Time Series DB)")
System_Ext(grafana, "Grafana", "Visualização de métricas e alertas")

Container_Boundary(system, "Sistema de Gestão de Ciclos de Estudo") {
    
    Component(frontend, "Frontend", "React/Next.js", "Interface do usuário.")
    ComponentDb(db, "Banco de Dados", "PostgreSQL", "Armazena dados do sistema.")

    Component(cicloCtrl, "Ciclo Controller", "REST Controller", "Expõe endpoints de ciclos.")
    Component(cicloSvc, "Ciclo Service", "Service", "Gerencia ciclos de estudo.")
    Component(cicloRepo, "Ciclo Repository", "Repository", "Acesso a dados de ciclos.")

    Component(discCtrl, "Disciplina Controller", "REST Controller", "Expõe endpoints de disciplinas.")
    Component(discSvc, "Disciplina Service", "Service", "Gerencia disciplinas.")
    Component(discRepo, "Disciplina Repository", "Repository", "Acesso a dados de disciplinas.")

    Component(revCtrl, "Revisao Controller", "REST Controller", "Expõe endpoints de revisões.")
    Component(revSvc, "Revisao Service", "Service", "Agenda revisões automáticas.")
    Component(revRepo, "Revisao Repository", "Repository", "Acesso a dados de revisões.")

    Component(estCtrl, "Estatistica Controller", "REST Controller", "Expõe endpoints de estatísticas.")
    Component(estSvc, "Estatistica Service", "Service", "Calcula estatísticas.")
    Component(estRepo, "Estatistica Repository", "Repository", "Leitura de métricas.")

    Component(userCtrl, "Usuario Controller", "REST Controller", "Expõe endpoints de usuário.")
    Component(userSvc, "Usuario Service", "Service", "Gerencia autenticação e usuários.")
    Component(autorizacaoProvider, "Autorizacao Provider", "Interface (Port)", "Especificaçoes para autorização")
    Component(oidcAdapter, "OIDC Adapter", "Component (Adapter)", "Implementa a comunicação OIDC")

    Component(notifCtrl, "Notificacao Controller", "REST Controller", "Expõe endpoints de notificação.")
    Component(notifSvc, "Notificacao Service", "Service", "Gerencia envio de notificações.")
    Component(notiProvider, "Notificação Provider", "Interface (Port)", "Especificaçoes para envio de mensagens")
    Component(emailAdapter, "Email Adapter", "Component (Adapter)", "Implementa o envio AWS/SMTP")

    Component(concursoCtrl, "Concurso Controller", "REST Controller", "Expõe endpoints dos concursos")
    Component(concursoSvc, "Concurso Service", "REST Controller", "Realiza busca por concursos")
    Component(concursoProvider, "Concurso Provider", "Interface (Port)", "Especificaçoes para acessar info concursos")
    Component(concursoAdapter, "Concurso Adapter", "Component (Adapter)", "Implementa Cliente da API de concursos")

    Component(metricsComp, "Metrics Exporter", "Spring Actuator / Micrometer", "Expõe endpoint /actuator/prometheus para scraping.")
}

Rel(user, frontend, "Acessa via navegador", "HTTPS")

Rel(frontend, cicloCtrl, "Gerencia ciclos", "HTTPS/JSON")
Rel(frontend, discCtrl, "Gerencia disciplinas", "HTTPS/JSON")
Rel(frontend, revCtrl, "Consulta revisões", "HTTPS/JSON")
Rel(frontend, estCtrl, "Obtém estatísticas", "HTTPS/JSON")
Rel(frontend, userCtrl, "Login/Cadastro", "HTTPS/JSON")
Rel(frontend, notifCtrl, "Configura notificações", "HTTPS/JSON")
Rel(frontend, concursoCtrl, "Consulta Concursos", "HTTPS/JSON")

Rel(cicloCtrl, cicloSvc, "Chama regras")
Rel(cicloSvc, cicloRepo, "Utiliza")
Rel(cicloRepo, db, "JPA")

Rel(discCtrl, discSvc, "Chama regras")
Rel(discSvc, discRepo, "Utiliza")
Rel(discRepo, db, "JPA")

Rel(revCtrl, revSvc, "Chama regras")
Rel(revSvc, revRepo, "Utiliza")
Rel(revRepo, db, "JPA")

Rel(estCtrl, estSvc, "Chama regras")
Rel(estSvc, estRepo, "Utiliza")
Rel(estRepo, db, "SQL")

Rel(userCtrl, userSvc, "Processa")
Rel(userSvc, autorizacaoProvider, "Usa (Abstração)")
Rel(autorizacaoProvider, oidcAdapter  , "Implementada por")
Rel(oidcAdapter,  authSystem, "HTTP")

Rel(notifCtrl, notifSvc, "Processa")
Rel(notifSvc, notiProvider, "Usa (Abstração)")
Rel(notiProvider, emailAdapter, "Implementada por")
Rel(emailAdapter, emailSystem, "HTTP")


Rel(concursoCtrl, concursoSvc, "Processa")
Rel(concursoSvc, concursoProvider, "Usa (Abstração)")
Rel(concursoProvider, concursoAdapter, "Implementada por")
Rel(concursoAdapter, concursosApi, "HTTP")

Rel(prometheus, metricsComp, "Scrape (Pull) de métricas", "HTTP/GET")
Rel(grafana, prometheus, "Consulta (PromQL)", "HTTP/JSON")
Rel(admin, grafana, "Visualiza Dashboards", "HTTPS")

@enduml